---
Name: mainsite
After: 'framework/*','cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
Email:
  admin_email: 'goProperty <admin@goproperty.co.nz>'
  noreply_email: 'goProperty <no-reply@goproperty.co.nz>'
SiteVersion:
  version: 1.0
SSViewer:
  theme: 'default'
Page:
  extensions:
    - OpenGraphExtension
    - TwitterCardExtension
    - SeoObjectExtension
    - SEOExtension
NewZealand:
  Regions:
    'Northland': 'Northland'
    'Auckland': 'Auckland'
    'Waikato': 'Waikato'
    'Bay Of Plenty': 'Bay Of Plenty'
    'Gisborne': 'Gisborne'
    "Hawke's Bay": "Hawke's Bay"
    'Taranaki': 'Taranaki'
    'Manawatu / Wanganui': 'Manawatu / Wanganui'
    'Wellington': 'Wellington'
    'Nelson / Tasman': 'Nelson / Tasman'
    'Marlborough': 'Marlborough'
    'West Coast': 'West Coast'
    'Canterbury': 'Canterbury'
    'Otago': 'Otago'
    'Southland': 'Southland'
SiteConfig:
  extensions:
    - CustomSiteConfig
    - OpenGraphExtension
    - TwitterCardExtension
Page_Controller:
  extensions:
    - PageControllerDecorator
ModelAdmin:
  extensions:
    - ModelAdminExtension
Member:
  Subscriptions:
    'Landlords': 15
    'Tradesmen': 25
    'Realtors': 35
  extensions:
    - AddressProperties
    - MemberExtension
SeoConfig:
    Page: true
    ErrorPage: false
    RedirectorPage: false
    VirtualPage: false
TradesPerson:
  WorkTypes:
    'electrical': 'Electrical'
    'builder': 'Builder'
    'carpenter': 'Carpenter'
    'plumber': 'Plumber'
    'mover': 'Mover'
PropertyPage:
  DailyCharge: 2
  MaxBedroom: 10
  MaxBathroom: 5
  MaxCapacity: 20
  RentForm:
    - 'Apartment'
    - 'House'
    - 'Townhouse'
    - 'Unit'
  SaleForm:
    - 'Apartment'
    - 'House'
    - 'Lifestyle bare land'
    - 'Lifestyle dwelling'
    - 'Section'
    - 'Townhouse'
    - 'Unit'
  Parking:
    - 'No carpark'
    - 'On-street'
    - 'Off-street'
    - 'Garage'
    - 'Carport'
    - 'Residential parking'
    - 'Coupon parking'
  IdealTenants:
    - 'Student'
    - 'Professional'
Image:
  extensions:
    - ImageExt
GoogleAPIs:
  Recaptcha: '6LcK8g8UAAAAAMspUwFUpvzBPZDgNN56AlUn6rqL'
  Recaptcha_site: '6LcK8g8UAAAAAHvUzsx9cEF4X8-OJEbVmamdkz06'
MenuSet:
  default_sets:
    - "Footer First-Menu"
    - "Footer Second-Menu"
    - "Footer Social-Menu"
SaltedPayment:
  DefaultOrderClass: 'Order'
  MerchantSettings:
    MerchantHomepageURL: "https://goprop.leochen.co.nz"
    SuccessURL: "https://goprop.leochen.co.nz/payment/success"
    FailureURL: "https://goprop.leochen.co.nz/payment/fail"
    CancellationURL: "https://goprop.leochen.co.nz/payment/cancel"
    CardSavedURL: "https://goprop.leochen.co.nz/member/action/creditcards"
    PaymentScheduledURL: "https://goprop.leochen.co.nz/payment/pending"
  GatewaySettings:
    Paystation:
        #HMacMode: '0',
        #HMacSecret: 'oXqsidB0IxFNyWev'
        pstn_pi: '615680'
