---
Name: mainsite
After: 'framework/*','cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SiteVersion:
  version: 1.0
SSViewer:
  theme: 'default'
Page:
  extensions:
    - OpenGraphExtension
    - TwitterCardExtension
    - SeoObjectExtension
    - SEOExtension
SiteConfig:
  extensions:
    - CustomSiteConfig
    - OpenGraphExtension
    - TwitterCardExtension
Page_Controller:
  extensions:
    - PageControllerDecorator
ModelAdmin:
  extensions:
    - ModelAdminExtension
Member:
  extensions:
    - AddressProperties
    - MemberExtension
SeoConfig:
    Page: true
    ErrorPage: false
    RedirectorPage: false
    VirtualPage: false
PropertyPage:
  MaxBedroom: 10
  MaxBathroom: 5
Image:
  extensions:
    - ImageExt
GoogleAPIs:
  Recaptcha: '6LcK8g8UAAAAAMspUwFUpvzBPZDgNN56AlUn6rqL'
  Recaptcha_site: '6LcK8g8UAAAAAHvUzsx9cEF4X8-OJEbVmamdkz06'
