---
Name: mainsite
After: 'framework/*','cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
Email:
  admin_email: 'GoProperty <admin@goproperty.co.nz>'
  noreply_email: 'GoProperty <no-reply@goproperty.co.nz>'
SiteVersion:
  version: 1.0
SSViewer:
  theme: 'default'
Page:
  extensions:
    - OpenGraphExtension
    - TwitterCardExtension
    - SeoObjectExtension
    - SEOExtension
DataList:
  extensions:
    - DataListExt
NewZealand:
  Regions:
    'Northland': 'Northland'
    'Auckland': 'Auckland'
    'Waikato': 'Waikato'
    'Bay Of Plenty': 'Bay Of Plenty'
    'Gisborne': 'Gisborne'
    "Hawke's Bay": "Hawke's Bay"
    'Taranaki': 'Taranaki'
    'Manawatu / Wanganui': 'Manawatu / Wanganui'
    'Wellington': 'Wellington'
    'Nelson / Tasman': 'Nelson / Tasman'
    'Marlborough': 'Marlborough'
    'West Coast': 'West Coast'
    'Canterbury': 'Canterbury'
    'Otago': 'Otago'
    'Southland': 'Southland'
SiteConfig:
  extensions:
    - CustomSiteConfig
    - OpenGraphExtension
    - TwitterCardExtension
Page_Controller:
  extensions:
    - PageControllerDecorator
ModelAdmin:
  extensions:
    - ModelAdminExtension
Member:
  Subscriptions:
    'Landlords': 15
    'Tradesmen': 25
    'Realtors': 35
  extensions:
    - AddressProperties
    - MemberExtension
SeoConfig:
    Page: true
    ErrorPage: false
    RedirectorPage: false
    VirtualPage: false
TradesPerson:
  WorkTypes:
    'electrical': 'Electrical'
    'builder': 'Builder'
    'carpenter': 'Carpenter'
    'plumber': 'Plumber'
    'mover': 'Mover'
Business:
  Subscriptions:
    '6 months': 45
    '1 year': 79.95
  Length:
    '6 months': 183
    '1 year': 365
PropertyPage:
  DailyCharge: 2
  TilSold: 29.95
  TilRented: 29.95
  MaxBedroom: 10
  MaxBathroom: 5
  MaxCapacity: 20
  RentForm:
    - 'Apartment'
    - 'House'
    - 'Townhouse'
    - 'Unit'
  SaleForm:
    - 'Apartment'
    - 'House'
    - 'Lifestyle bare land'
    - 'Lifestyle dwelling'
    - 'Section'
    - 'Townhouse'
    - 'Unit'
  Parking:
    - 'No carpark'
    - 'On-street'
    - 'Off-street'
    - 'Garage'
    - 'Carport'
    - 'Residential parking'
    - 'Coupon parking'
  IdealTenants:
    - 'Student'
    - 'Professional'
Property:
  DailyCharge: 2
  TilSold: 29.95
  TilRented: 29.95
  MaxBedroom: 10
  MaxBathroom: 5
  MaxCapacity: 20
  Basic:
    'Apartment': 'Apartment'
    'House': 'House'
    'Townhouse': 'Townhouse'
    'Unit': 'Unit'
  Advanced:
    'Section': 'Section'
    'Lifestyle bare land': 'Lifestyle bare land'
    'Lifestyle dwelling': 'Lifestyle dwelling'
  Parking:
    'No carpark': 'No carpark'
    'On-street': 'On-street'
    'Off-street': 'Off-street'
    'Garage': 'Garage'
    'Carport': 'Carport'
    'Residential parking': 'Residential parking'
    'Coupon parking': 'Coupon parking'
  IdealTenants:
    'Student': 'Student'
    'Professional': 'Professional'
Listing:
  extensions:
    - Versioned("Stage","Live")
Image:
  extensions:
    - ImageExt
GoogleAPIs:
  Recaptcha: '6LcK8g8UAAAAAMspUwFUpvzBPZDgNN56AlUn6rqL'
  Recaptcha_site: '6LcK8g8UAAAAAHvUzsx9cEF4X8-OJEbVmamdkz06'
  Map: 'AIzaSyC0iYnTDuwXR7d1hdo1Gd-QTCFfqoAyNR4'
MenuSet:
  default_sets:
    - "Footer First-Menu"
    - "Footer Second-Menu"
    - "Footer Social-Menu"
Ads:
  Position:
    'home-top': 'Homepage top'
    'home-middle': 'Homepage middle'
    'home-bottom': 'Homepage bottom'

SaltedPayment:
  DefaultOrderClass: 'Order'
  MerchantSettings:
    MerchantHomepageURL: "https://goprop.leochen.co.nz"
    SuccessURL: "https://goprop.leochen.co.nz/payment/success"
    FailureURL: "https://goprop.leochen.co.nz/payment/fail"
    CancellationURL: "https://goprop.leochen.co.nz/payment/cancel"
    CardSavedURL: "https://goprop.leochen.co.nz/member/action/creditcards"
    PaymentScheduledURL: "https://goprop.leochen.co.nz/payment/pending"
  GatewaySettings:
    Paystation:
        #HMacMode: '0',
        #HMacSecret: 'O6cS8Y52pb5fbEz6'
        pstn_pi: '615812'
        pstn_tm: 't'
LeftAndMain:
  extensions:
    - LeftMainDecorator
