---
Name: apiroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'signup': 'Signup'
    'signin': 'Signin'
    'member': 'Dashboard'
    'checkout/complete': 'PaystationController'
    'api/v1/payment/$ID': 'PaymentAPI'
    'api/v1/creditcard/$ID': 'CreditcardAPI'
    'api/v1/agency/$ID': 'AgencyAPI'
