---
Name: apiroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'signup': 'Signup'
    'signin': 'Signin'
    'member': 'Dashboard'
    'api/v1/fav': 'FavAPI'
    'api/v1/eoi/$ID/$Action': 'InterestAPI'
    'api/v1/service-request/$ID/$Action': 'ServiceRequestAPI'
    'api/v1/appointment/$ID/$Action': 'AppointmentAPI'
    'api/v1/payment/$ID': 'PaymentAPI'
    'api/v1/creditcard/$ID': 'CreditcardAPI'
    'api/v1/agency/$ID': 'AgencyAPI'
    'api/v1/rental/$ID/$PROPERTYID': 'RentalAPI'
    'api/v1/rating/$Type/$ID': 'RatingAPI'
    'api/v1/service/$Title': 'ServiceAPI'
    'api/v1/location/$district/$suburb': 'LocationAPI'
    'api/v1/listing/$ID/$Action': 'ListingAPI'
    'api/v1/property-page/$ID/$Action': 'OldPropertyAPI'
    'list/$region/$district/$suburb/$ID': 'PropertyLister'
    'tradesmen/$region/$district/$suburb/$slug': 'TradesmenLister'
    'payment/$status': 'GatewayController'
    'feedback/$ID': 'FeedbackInvitationController'
