---
Name: apiroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'signup': 'Signup'
    'signin': 'Signin'
    'member': 'Dashboard'
    'api/v1/payment/$ID': 'PaymentAPI'
    'api/v1/creditcard/$ID': 'CreditcardAPI'
    'api/v1/agency/$ID': 'AgencyAPI'
    'api/v1/service/$Title': 'ServiceAPI'
    'api/v1/location/$district/$suburb': 'LocationAPI'
    'list/$region/$district/$suburb/$ID': 'PropertyLister'
    'tradesmen/$region/$district/$suburb/$slug': 'TradesmenLister'
    'payment/$status': 'GatewayController'
