---
Name: apiroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'signup': 'Signup'
    'signin': 'Signin'
    'member': 'Dashboard'
    'checkout/complete': 'PaystationController'
